### ISSUE TITLE
Failing to load correctly

### ISSUE THREAD

**Issue by ClownFrownGuy** [ToCraft/craftedcore#13]
### Mod loader

NeoForge

### Minecraft version

1.20.6

### CraftedCore version

4.2.3

### Modloader version

4.5.1

### The latest.log file

[15:12:55] [main/INFO]: ModLauncher running: args [--username, ClownFrownGuy, --version, neoforge-20.6.111-beta, --gameDir, C:\Users\colea\AppData\Roaming\.minecraft, --assetsDir, C:\Users\colea\AppData\Roaming\.minecraft\assets, --assetIndex, 16, --uuid, b855ffcf969d4910943efb11eb5a39a1, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, NGNjNTlmMGMtNDBlMS00MjdhLWFkNGItZTQ3MDliYzljMWQ1, --xuid, 2535434931232429, --userType, msa, --versionType, release, --quickPlayPath, C:\Users\colea\AppData\Roaming\.minecraft\quickPlay\java\1717711973791.json, --fml.neoForgeVersion, 20.6.111-beta, --fml.fmlVersion, 3.0.45, --fml.mcVersion, 1.20.6, --fml.neoFormVersion, 20240429.153634, --launchTarget, forgeclient]
[15:12:55] [main/INFO]: JVM identified as Microsoft OpenJDK 64-Bit Server VM 21.0.3+9-LTS
[15:12:55] [main/INFO]: ModLauncher 11.0.2+main.4612c65f starting: java version 21.0.3 by Microsoft; OS Windows 11 arch amd64 version 10.0
[15:12:55] [main/INFO]: Loading ImmediateWindowProvider fmlearlywindow
[15:12:56] [main/INFO]: Trying GL version 4.6
[15:12:56] [main/INFO]: Requested GL version 4.6 got version 4.6
[15:12:56] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/colea/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.13.4+mixin.0.8.5/sponge-mixin-0.13.4+mixin.0.8.5.jar%23117!/ Service=ModLauncher Env=CLIENT
[15:12:56] [pool-2-thread-1/INFO]: GL info: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 537.70, NVIDIA Corporation
[15:12:56] [main/INFO]: Found mod file "client-1.20.6-20240429.153634-srg.jar" [locator: production client provider +net.neoforged:neoforge:20.6.111-beta:client]
[15:12:56] [main/INFO]: Found mod file "neoforge-20.6.111-beta-universal.jar" [locator: PathBasedLocator[name=neoforge, paths=[C:\Users\colea\AppData\Roaming\.minecraft\libraries\net\neoforged\neoforge\20.6.111-beta\neoforge-20.6.111-beta-universal.jar]], reader: mod manifest]
[15:12:56] [main/INFO]: Found mod file "craftedcore-4.2.3-neoforge.jar" [locator: {mods folder locator at C:\Users\colea\AppData\Roaming\.minecraft\mods}, reader: mod manifest]
[15:12:56] [main/INFO]: Found mod file "remorphed-3.6.3-neoforge.jar" [locator: {mods folder locator at C:\Users\colea\AppData\Roaming\.minecraft\mods}, reader: mod manifest]
[15:12:56] [main/INFO]: Found mod file "walkers-4.5.1+build.1-neoforge.jar" [locator: {mods folder locator at C:\Users\colea\AppData\Roaming\.minecraft\mods}, reader: mod manifest]
[15:12:56] [main/INFO]: Found 1 dependencies adding them to mods collection
[15:12:56] [main/INFO]: Found gamelibrary file "mixinextras-neoforge-0.3.5.jar" [parent: neoforge-20.6.111-beta-universal.jar, locator: jarinjar, reader: mod manifest]
[15:12:57] [main/INFO]: Loading coremod script-engine for [neoforge]
[15:12:58] [main/INFO]: Compatibility level set to JAVA_17
[15:12:58] [main/INFO]: Launching target 'forgeclient' with arguments [--version, neoforge-20.6.111-beta, --gameDir, C:\Users\colea\AppData\Roaming\.minecraft, --assetsDir, C:\Users\colea\AppData\Roaming\.minecraft\assets, --uuid, b855ffcf969d4910943efb11eb5a39a1, --username, ClownFrownGuy, --assetIndex, 16, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, NGNjNTlmMGMtNDBlMS00MjdhLWFkNGItZTQ3MDliYzljMWQ1, --xuid, 2535434931232429, --userType, msa, --versionType, release, --quickPlayPath, C:\Users\colea\AppData\Roaming\.minecraft\quickPlay\java\1717711973791.json]
[15:12:58] [main/WARN]: Error loading class: net/bettercombat/compatibility/CompatibilityFlags (java.lang.ClassNotFoundException: net.bettercombat.compatibility.CompatibilityFlags)
[06Jun2024 15:12:59.673] [pool-8-thread-1/INFO] [MixinExtras|Service/]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[06Jun2024 15:13:03.005] [pool-8-thread-1/INFO] [mixin/]: walkers.mixins.json:accessor.DolphinAccessor from mod walkers->@Accessor[FIELD_GETTER]::getSWIM_WITH_PLAYER_TARGETING()Lnet/minecraft/world/entity/ai/targeting/TargetingConditions; should be static as its target is
[06Jun2024 15:13:03.112] [Datafixer Bootstrap/INFO] [com.mojang.datafixers.DataFixerBuilder/]: 225 Datafixer optimizations took 227 milliseconds
[06Jun2024 15:13:04.717] [Render thread/WARN] [net.minecraft.server.packs.VanillaPackResourcesBuilder/]: Assets URL 'union:/C:/Users/colea/AppData/Roaming/.minecraft/libraries/net/minecraft/client/1.20.6-20240429.153634/client-1.20.6-20240429.153634-srg.jar%23188!/assets/.mcassetsroot' uses unexpected schema
[06Jun2024 15:13:04.718] [Render thread/WARN] [net.minecraft.server.packs.VanillaPackResourcesBuilder/]: Assets URL 'union:/C:/Users/colea/AppData/Roaming/.minecraft/libraries/net/minecraft/client/1.20.6-20240429.153634/client-1.20.6-20240429.153634-srg.jar%23188!/data/.mcassetsroot' uses unexpected schema
[06Jun2024 15:13:04.745] [Render thread/INFO] [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService/]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[06Jun2024 15:13:04.754] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: ClownFrownGuy
[06Jun2024 15:13:04.836] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Backend library: LWJGL version 3.3.3+5
[06Jun2024 15:13:05.006] [modloading-worker-0/ERROR] [net.neoforged.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: craftedcore, class tocraft.craftedcore.neoforge.CraftedCoreNeoForge
java.lang.NoClassDefFoundError: net/neoforged/neoforge/client/event/RenderGuiOverlayEvent$Pre
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3578) ~[?:?]
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2676) ~[?:?]
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.register(EventBus.java:85) ~[bus-8.0.1.jar%23108!/:?]
	at TRANSFORMER/craftedcore@4.2.3/tocraft.craftedcore.neoforge.client.CraftedCoreNeoForgeClient.<init>(CraftedCoreNeoForgeClient.java:11) ~[craftedcore-4.2.3-neoforge.jar%23190!/:?]
	at TRANSFORMER/craftedcore@4.2.3/tocraft.craftedcore.neoforge.CraftedCoreNeoForge.<init>(CraftedCoreNeoForge.java:19) ~[craftedcore-4.2.3-neoforge.jar%23190!/:?]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at MC-BOOTSTRAP/fml_loader@3.0.45/net.neoforged.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:109) ~[loader-3.0.45.jar%23101!/:3.0]
	at MC-BOOTSTRAP/fml_loader@3.0.45/net.neoforged.fml.ModLoader.lambda$constructMods$3(ModLoader.java:157) ~[loader-3.0.45.jar%23101!/:3.0]
	at MC-BOOTSTRAP/fml_loader@3.0.45/net.neoforged.fml.ModLoader.lambda$dispatchParallelTask$7(ModLoader.java:235) ~[loader-3.0.45.jar%23101!/:3.0]
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) [?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) [?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) [?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]
Caused by: java.lang.ClassNotFoundException: net.neoforged.neoforge.client.event.RenderGuiOverlayEvent$Pre
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:220) ~[securejarhandler-3.0.7.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 20 more
[06Jun2024 15:13:05.020] [modloading-worker-0/INFO] [net.neoforged.neoforge.common.NeoForgeMod/NEOFORGE-MOD]: NeoForge mod loading, version 20.6.111-beta, for MC 1.20.6
[06Jun2024 15:13:05.205] [Render thread/FATAL] [net.neoforged.fml.ModLoader/LOADING]: Failed to wait for future Mod Construction, 1 errors found
[06Jun2024 15:13:05.322] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.sound.SoundEngineLoadEvent to a broken mod state
[06Jun2024 15:13:05.416] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.RegisterColorHandlersEvent$Block to a broken mod state
[06Jun2024 15:13:05.419] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.RegisterColorHandlersEvent$Item to a broken mod state
[06Jun2024 15:13:05.470] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.RegisterRenderBuffersEvent to a broken mod state
[06Jun2024 15:13:05.524] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.RegisterParticleProvidersEvent to a broken mod state
[06Jun2024 15:13:05.547] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.RenderLevelStageEvent$RegisterStageEvent to a broken mod state
[06Jun2024 15:13:05.597] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.RegisterSpriteSourceTypesEvent to a broken mod state
[06Jun2024 15:13:05.618] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.RegisterMenuScreensEvent to a broken mod state
[06Jun2024 15:13:05.618] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.RegisterClientReloadListenersEvent to a broken mod state
[06Jun2024 15:13:05.619] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.EntityRenderersEvent$RegisterLayerDefinitions to a broken mod state
[06Jun2024 15:13:05.619] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.EntityRenderersEvent$RegisterRenderers to a broken mod state
[06Jun2024 15:13:05.620] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.RegisterClientTooltipComponentFactoriesEvent to a broken mod state
[06Jun2024 15:13:05.620] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.RegisterEntitySpectatorShadersEvent to a broken mod state
[06Jun2024 15:13:05.620] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.RegisterKeyMappingsEvent to a broken mod state
[06Jun2024 15:13:05.622] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.RegisterRecipeBookCategoriesEvent to a broken mod state
[06Jun2024 15:13:05.623] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.RegisterGuiLayersEvent to a broken mod state
[06Jun2024 15:13:05.624] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.RegisterDimensionSpecialEffectsEvent to a broken mod state
[06Jun2024 15:13:05.625] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.RegisterNamedRenderTypesEvent to a broken mod state
[06Jun2024 15:13:05.626] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.RegisterColorHandlersEvent$ColorResolvers to a broken mod state
[06Jun2024 15:13:05.627] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.RegisterItemDecorationsEvent to a broken mod state
[06Jun2024 15:13:05.633] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.RegisterPresetEditorsEvent to a broken mod state
[06Jun2024 15:13:05.699] [Render thread/INFO] [net.minecraft.server.packs.resources.ReloadableResourceManager/]: Reloading ResourceManager: vanilla, file/VanillaTweaks_r995535.zip, file/VanillaTweaks_r974373.zip
[06Jun2024 15:13:05.740] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.ModelEvent$RegisterGeometryLoaders to a broken mod state
[06Jun2024 15:13:05.787] [Worker-Main-3/INFO] [net.minecraft.client.gui.font.providers.UnihexProvider/]: Found unifont_all_no_pua-15.1.04.hex, loading
[06Jun2024 15:13:05.907] [Worker-Main-6/INFO] [net.minecraft.client.gui.font.providers.UnihexProvider/]: Found unifont_jp_patch-15.1.04.hex, loading
[06Jun2024 15:13:06.567] [Worker-Main-4/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.ModelEvent$RegisterAdditional to a broken mod state
[06Jun2024 15:13:07.156] [Worker-Main-4/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.ModelEvent$ModifyBakingResult to a broken mod state
[06Jun2024 15:13:07.230] [Render thread/WARN] [net.minecraft.client.sounds.SoundEngine/]: Missing sound for event: minecraft:item.goat_horn.play
[06Jun2024 15:13:07.231] [Render thread/WARN] [net.minecraft.client.sounds.SoundEngine/]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[06Jun2024 15:13:07.967] [Render thread/INFO] [com.mojang.blaze3d.audio.Library/]: OpenAL initialized on device OpenAL Soft on Headphones (Realtek(R) Audio)
[06Jun2024 15:13:07.967] [Render thread/INFO] [net.minecraft.client.sounds.SoundEngine/SOUNDS]: Sound engine started
[06Jun2024 15:13:07.968] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.sound.SoundEngineLoadEvent to a broken mod state
[06Jun2024 15:13:08.078] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[06Jun2024 15:13:08.088] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.TextureAtlasStitchedEvent to a broken mod state
[06Jun2024 15:13:08.088] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[06Jun2024 15:13:08.088] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.TextureAtlasStitchedEvent to a broken mod state
[06Jun2024 15:13:08.089] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[06Jun2024 15:13:08.089] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.TextureAtlasStitchedEvent to a broken mod state
[06Jun2024 15:13:08.089] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[06Jun2024 15:13:08.090] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.TextureAtlasStitchedEvent to a broken mod state
[06Jun2024 15:13:08.090] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[06Jun2024 15:13:08.094] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.TextureAtlasStitchedEvent to a broken mod state
[06Jun2024 15:13:08.094] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[06Jun2024 15:13:08.094] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.TextureAtlasStitchedEvent to a broken mod state
[06Jun2024 15:13:08.094] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[06Jun2024 15:13:08.095] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.TextureAtlasStitchedEvent to a broken mod state
[06Jun2024 15:13:08.095] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[06Jun2024 15:13:08.095] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.TextureAtlasStitchedEvent to a broken mod state
[06Jun2024 15:13:08.095] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[06Jun2024 15:13:08.096] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.TextureAtlasStitchedEvent to a broken mod state
[06Jun2024 15:13:08.096] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.ModelEvent$BakingCompleted to a broken mod state
[06Jun2024 15:13:08.208] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[06Jun2024 15:13:08.209] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[06Jun2024 15:13:08.285] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[06Jun2024 15:13:08.288] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[06Jun2024 15:13:08.289] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[06Jun2024 15:13:08.290] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[06Jun2024 15:13:08.291] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[06Jun2024 15:13:08.291] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[06Jun2024 15:13:08.293] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[06Jun2024 15:13:08.294] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[06Jun2024 15:13:08.295] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[06Jun2024 15:13:08.295] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[06Jun2024 15:13:08.296] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[06Jun2024 15:13:08.296] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[06Jun2024 15:13:08.297] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[06Jun2024 15:13:08.298] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[06Jun2024 15:13:08.298] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[06Jun2024 15:13:08.298] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[06Jun2024 15:13:08.312] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[06Jun2024 15:13:08.313] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[06Jun2024 15:13:08.318] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[06Jun2024 15:13:08.318] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[06Jun2024 15:13:08.318] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.EntityRenderersEvent$AddLayers to a broken mod state
[06Jun2024 15:13:08.318] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[06Jun2024 15:13:08.318] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.TextureAtlasStitchedEvent to a broken mod state
[06Jun2024 15:13:08.319] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[06Jun2024 15:13:08.319] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.TextureAtlasStitchedEvent to a broken mod state
[06Jun2024 15:13:08.320] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[06Jun2024 15:13:08.320] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.TextureAtlasStitchedEvent to a broken mod state
[06Jun2024 15:13:08.320] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 64x64x0 minecraft:textures/atlas/map_decorations.png-atlas
[06Jun2024 15:13:08.320] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.TextureAtlasStitchedEvent to a broken mod state
[06Jun2024 15:13:08.320] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 1024x512x0 minecraft:textures/atlas/gui.png-atlas
[06Jun2024 15:13:08.321] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.TextureAtlasStitchedEvent to a broken mod state
[06Jun2024 15:13:08.345] [Render thread/WARN] [net.minecraft.client.renderer.ShaderInstance/]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[06Jun2024 15:13:08.386] [Render thread/ERROR] [net.neoforged.fml.ModLoader/]: Cowardly refusing to send event net.neoforged.neoforge.client.event.RegisterShadersEvent to a broken mod state
[06Jun2024 15:13:08.461] [Render thread/FATAL] [net.neoforged.neoforge.common.NeoForgeMod/]: Preparing crash report with UUID 0af0ef75-fac5-4f46-be88-3e1cff8b5f61
[06Jun2024 15:13:08.462] [Render thread/FATAL] [net.neoforged.neoforge.client.loading.ClientModLoader/]: Crash report saved to C:\Users\colea\AppData\Roaming\.minecraft\crash-reports\crash-2024-06-06_15.13.08-fml.txt
[06Jun2024 15:13:08.464] [Render thread/FATAL] [net.neoforged.neoforge.common.NeoForgeMod/]: Preparing crash report with UUID 3ebb338d-6166-4890-a281-1ffc160eaa3f

### Issue description

I am decently new to Minecraft Mods, but when I went to open Minecraft with NeoForge, when it came up it said that Crafted Forge has failed to load properly. I don't know if this does much, but I have ran Jarfix, tried re-downloading the file, and even starting the process over again but it still says this. Please tell me how to fix this.

**Comment by ClownFrownGuy** [comment]
Just in case this helps, this is what I'm looking at:
![06 06 2024_15 31 08_REC](https://github.com/ToCraft/craftedcore/assets/171987524/643daf54-395b-498a-a260-c0249e27da50)

**Comment by ToCraft** [comment]
Yeah, I've got to update to the newest NeoForge version. Until then, you can use NeoForge 20.6.1-beta.

**Comment by ClownFrownGuy** [comment]
Alright, no problem and thank you

**Comment by ToCraft** [comment]
Fixed as of 29c3b48541c330ff995391c83eefbc97ea87560b.
(CraftedCore 4.2.4)
